name: Pull Request
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DATABASE_URL: "postgresql://postgres:postgres@event_management_postgres:5432/event_management_db_test"
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "event_management_db_test"
          envkey_JWT_SECRET: "12345"
          file_name: ".env.test"
      - name: Run E2E tests
        run: docker-compose -f docker-compose-tests.yml run event_management_app npm run test:e2e
